# Generated by Django 6.0.3 on 2026-03-04 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours', models.FloatField(help_text='Daily study hours (0-24)')),
                ('self_study_hours', models.FloatField(help_text='Weekly self-study hours (0-40)')),
                ('online_class_hours', models.FloatField(help_text='Weekly online class hours')),
                ('attendance_percentage', models.FloatField(help_text='Attendance % (0-100)')),
                ('class_participation', models.FloatField(help_text='Participation score (0-10)')),
                ('social_media_hours', models.FloatField(help_text='Daily social media usage (hours)')),
                ('gaming_hours', models.FloatField(help_text='Daily gaming hours')),
                ('total_screen_time', models.FloatField(help_text='Total daily screen time (hours)')),
                ('sleep_hours', models.FloatField(help_text='Daily sleep hours')),
                ('exercise_minutes', models.FloatField(help_text='Daily exercise (minutes)')),
                ('caffeine_intake', models.FloatField(help_text='Daily caffeine intake (mg)')),
                ('mental_health_score', models.FloatField(help_text='Mental health score (1-10)')),
                ('part_time_job', models.BooleanField(default=False, help_text='Has a part-time job?')),
                ('upcoming_deadlines', models.IntegerField(default=0, help_text='Number of upcoming deadlines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
