# Generated by Django 6.0.3 on 2026-05-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
