"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5ndnyo=2$736ak8f^q%f9ovg3svl%7bx67f+*_dq%!sv!al%08'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# =============================================================================
# 1) Application definition — Register our custom apps + third-party packages
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',               # Django REST Framework
    'rest_framework_simplejwt',      # JWT Authentication
    'corsheaders',                   # CORS Headers for React frontend

    # Our custom apps
    'core',                          # Custom User model
    'students',                      # Student records
    'predictions',                   # ML predictions
]


# =============================================================================
# 2) Middleware — Added CORS middleware at the top
# =============================================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',           # <-- Must be at top!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# =============================================================================
# 3) Database — Using SQLite for now, will switch to Supabase PostgreSQL later
# =============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- Supabase PostgreSQL config (uncomment when ready) ---
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres.xxxxxxxx',
#         'PASSWORD': 'your-supabase-password',
#         'HOST': 'db.xxxxxxxx.supabase.co',
#         'PORT': '5432',
#     }
# }


# =============================================================================
# 4) Custom User Model — Tells Django to use our model instead of the default
# =============================================================================

AUTH_USER_MODEL = 'core.User'


# =============================================================================
# 5) Django REST Framework — Global settings for all API views
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# =============================================================================
# 6) SimpleJWT — Token expiry settings
# =============================================================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),      # Token valid for 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),          # Refresh valid for 7 days
    'ROTATE_REFRESH_TOKENS': True,                        # Get new refresh on use
    'AUTH_HEADER_TYPES': ('Bearer',),                     # Authorization: Bearer <token>
}


# =============================================================================
# 7) CORS — Allow React frontend to talk to Django backend
# =============================================================================

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',      # Vite dev server (React)
    'http://localhost:3000',      # Alternate React dev server
]
CORS_ALLOW_CREDENTIALS = True


# =============================================================================
# Password validation
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================================
# Internationalization
# =============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'    # Set to Indian timezone
USE_I18N = True
USE_TZ = True


# =============================================================================
# Static files (CSS, JavaScript, Images)
# =============================================================================

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
